2016/09/13 20:16:23 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\testyii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/testyii/index.php?r=gii
---
2016/09/13 20:28:04 [error] [php] include(Pengguna.php): failed to open stream: No such file or directory (C:\xampp\htdocs\yii\framework\YiiBase.php:432)
Stack trace:
#0 C:\xampp\htdocs\testyii\protected\components\UserIdentity.php(23): spl_autoload_call()
#1 C:\xampp\htdocs\testyii\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#2 C:\xampp\htdocs\yii\framework\validators\CInlineValidator.php(42): LoginForm->authenticate()
#3 C:\xampp\htdocs\yii\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute()
#4 C:\xampp\htdocs\yii\framework\base\CModel.php(159): CInlineValidator->validate()
#5 C:\xampp\htdocs\testyii\protected\controllers\SiteController.php(94): LoginForm->validate()
#6 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#7 C:\xampp\htdocs\yii\framework\web\CController.php(311): CInlineAction->runWithParams()
#8 C:\xampp\htdocs\yii\framework\web\CController.php(289): SiteController->runAction()
#9 C:\xampp\htdocs\yii\framework\web\CController.php(268): SiteController->runActionWithFilters()
#10 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): SiteController->run()
#11 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#12 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#13 C:\xampp\htdocs\testyii\index.php(13): CWebApplication->run()
REQUEST_URI=/testyii/index.php/site/login
in C:\xampp\htdocs\testyii\protected\components\UserIdentity.php (23)
in C:\xampp\htdocs\testyii\protected\models\LoginForm.php (52)
in C:\xampp\htdocs\testyii\protected\controllers\SiteController.php (94)
2016/09/13 20:38:19 [error] [php] include(Pengguna.php): failed to open stream: No such file or directory (C:\xampp\htdocs\yii\framework\YiiBase.php:432)
Stack trace:
#0 C:\xampp\htdocs\testyii\protected\components\UserIdentity.php(23): spl_autoload_call()
#1 C:\xampp\htdocs\testyii\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#2 C:\xampp\htdocs\yii\framework\validators\CInlineValidator.php(42): LoginForm->authenticate()
#3 C:\xampp\htdocs\yii\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute()
#4 C:\xampp\htdocs\yii\framework\base\CModel.php(159): CInlineValidator->validate()
#5 C:\xampp\htdocs\testyii\protected\controllers\SiteController.php(94): LoginForm->validate()
#6 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#7 C:\xampp\htdocs\yii\framework\web\CController.php(311): CInlineAction->runWithParams()
#8 C:\xampp\htdocs\yii\framework\web\CController.php(289): SiteController->runAction()
#9 C:\xampp\htdocs\yii\framework\web\CController.php(268): SiteController->runActionWithFilters()
#10 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): SiteController->run()
#11 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#12 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#13 C:\xampp\htdocs\testyii\index.php(13): CWebApplication->run()
REQUEST_URI=/testyii/index.php/site/login
in C:\xampp\htdocs\testyii\protected\components\UserIdentity.php (23)
in C:\xampp\htdocs\testyii\protected\models\LoginForm.php (52)
in C:\xampp\htdocs\testyii\protected\controllers\SiteController.php (94)
2016/09/13 20:48:36 [error] [php] include(Pengguna.php): failed to open stream: No such file or directory (C:\xampp\htdocs\yii\framework\YiiBase.php:432)
Stack trace:
#0 C:\xampp\htdocs\testyii\protected\components\UserIdentity.php(22): spl_autoload_call()
#1 C:\xampp\htdocs\testyii\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#2 C:\xampp\htdocs\yii\framework\validators\CInlineValidator.php(42): LoginForm->authenticate()
#3 C:\xampp\htdocs\yii\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute()
#4 C:\xampp\htdocs\yii\framework\base\CModel.php(159): CInlineValidator->validate()
#5 C:\xampp\htdocs\testyii\protected\controllers\SiteController.php(94): LoginForm->validate()
#6 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#7 C:\xampp\htdocs\yii\framework\web\CController.php(311): CInlineAction->runWithParams()
#8 C:\xampp\htdocs\yii\framework\web\CController.php(289): SiteController->runAction()
#9 C:\xampp\htdocs\yii\framework\web\CController.php(268): SiteController->runActionWithFilters()
#10 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): SiteController->run()
#11 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#12 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#13 C:\xampp\htdocs\testyii\index.php(13): CWebApplication->run()
REQUEST_URI=/testyii/index.php/site/login
in C:\xampp\htdocs\testyii\protected\components\UserIdentity.php (22)
in C:\xampp\htdocs\testyii\protected\models\LoginForm.php (52)
in C:\xampp\htdocs\testyii\protected\controllers\SiteController.php (94)
2016/09/13 20:49:54 [error] [php] Trying to get property of non-object (C:\xampp\htdocs\testyii\protected\components\UserIdentity.php:29)
Stack trace:
#0 C:\xampp\htdocs\yii\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute()
#1 C:\xampp\htdocs\yii\framework\base\CModel.php(159): CInlineValidator->validate()
#2 C:\xampp\htdocs\testyii\protected\controllers\SiteController.php(94): LoginForm->validate()
#3 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#4 C:\xampp\htdocs\yii\framework\web\CController.php(311): CInlineAction->runWithParams()
#5 C:\xampp\htdocs\yii\framework\web\CController.php(289): SiteController->runAction()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(268): SiteController->runActionWithFilters()
#7 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): SiteController->run()
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\testyii\index.php(13): CWebApplication->run()
REQUEST_URI=/testyii/index.php/site/login
in C:\xampp\htdocs\testyii\protected\components\UserIdentity.php (29)
in C:\xampp\htdocs\testyii\protected\models\LoginForm.php (52)
in C:\xampp\htdocs\testyii\protected\controllers\SiteController.php (94)
2016/09/13 20:52:21 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\framework\web\CController.php(1148): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\framework\web\CController.php(294): CFilterChain->run()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(268): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('admin')
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user/admin')
#9 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\testyii\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/testyii/index.php/user/admin
HTTP_REFERER=http://localhost/testyii/index.php/site/login
---
2016/09/13 21:00:48 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1130] Host '36.81.47.153' is not allowed to connect to this MySQL server' in C:\xampp\htdocs\yii\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\yii\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\yii\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(459): CModule->getComponent('db')
#4 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(637): CApplication->getDb()
#5 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(670): CActiveRecord->getDbConnection()
#6 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(1601): CActiveRecord->getCommandBuilder()
#7 C:\xampp\htdocs\yii\framework\web\CActiveDataProvider.php(228): CActiveRecord->count(Object(CDbCriteria))
#8 C:\xampp\htdocs\yii\framework\web\CDataProvider.php(224): CActiveDataProvider->calculateTotalItemCount()
#9 C:\xampp\htdocs\yii\framework\web\CActiveDataProvider.php(178): CDataProvider->getTotalItemCount()
#10 C:\xampp\htdocs\yii\framework\web\CDataProvider.php(168): CActiveDataProvider->fetchData()
#11 C:\xampp\htdocs\yii\framework\zii\widgets\CBaseListView.php(125): CDataProvider->getData()
#12 C:\xampp\htdocs\yii\framework\zii\widgets\CListView.php(211): CBaseListView->init()
#13 C:\xampp\htdocs\yii\framework\web\CBaseController.php(147): CListView->init()
#14 C:\xampp\htdocs\yii\framework\web\CBaseController.php(180): CBaseController->createWidget('zii.widgets.CLi...', Array)
#15 C:\xampp\htdocs\testyii\protected\views\member\index.php(20): CBaseController->widget('zii.widgets.CLi...', Array)
#16 C:\xampp\htdocs\yii\framework\web\CBaseController.php(126): require('C:\xampp\htdocs...')
#17 C:\xampp\htdocs\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#18 C:\xampp\htdocs\yii\framework\web\CController.php(872): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#19 C:\xampp\htdocs\yii\framework\web\CController.php(785): CController->renderPartial('index', Array, true)
#20 C:\xampp\htdocs\testyii\protected\controllers\MemberController.php(128): CController->render('index', Array)
#21 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): MemberController->actionIndex()
#22 C:\xampp\htdocs\yii\framework\web\CController.php(311): CInlineAction->runWithParams(Array)
#23 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#24 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#25 C:\xampp\htdocs\yii\framework\web\CController.php(1148): CFilter->filter(Object(CFilterChain))
#26 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#27 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#28 C:\xampp\htdocs\yii\framework\web\CController.php(294): CFilterChain->run()
#29 C:\xampp\htdocs\yii\framework\web\CController.php(268): CController->runActionWithFilters(Object(CInlineAction), Array)
#30 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('')
#31 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('member')
#32 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#33 C:\xampp\htdocs\testyii\index.php(13): CApplication->run()
#34 {main}
REQUEST_URI=/testyii/index.php/member
HTTP_REFERER=http://localhost/testyii/index.php/site/index
---
2016/09/13 21:39:38 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'sql6135708.Member' doesn't exist. The SQL statement executed was: SHOW FULL COLUMNS FROM `Member`.
in C:\xampp\htdocs\testyii\protected\views\member\index.php (20)
in C:\xampp\htdocs\testyii\protected\controllers\MemberController.php (128)
in C:\xampp\htdocs\testyii\index.php (13)
2016/09/13 21:39:38 [error] [exception.CDbException] exception 'CDbException' with message 'The table "Member" for active record class "Member" cannot be found in the database.' in C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php:2387
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Member))
#1 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(661): CActiveRecord->getMetaData()
#2 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(1606): CActiveRecord->getTableSchema()
#3 C:\xampp\htdocs\yii\framework\web\CActiveDataProvider.php(228): CActiveRecord->count(Object(CDbCriteria))
#4 C:\xampp\htdocs\yii\framework\web\CDataProvider.php(224): CActiveDataProvider->calculateTotalItemCount()
#5 C:\xampp\htdocs\yii\framework\web\CActiveDataProvider.php(178): CDataProvider->getTotalItemCount()
#6 C:\xampp\htdocs\yii\framework\web\CDataProvider.php(168): CActiveDataProvider->fetchData()
#7 C:\xampp\htdocs\yii\framework\zii\widgets\CBaseListView.php(125): CDataProvider->getData()
#8 C:\xampp\htdocs\yii\framework\zii\widgets\CListView.php(211): CBaseListView->init()
#9 C:\xampp\htdocs\yii\framework\web\CBaseController.php(147): CListView->init()
#10 C:\xampp\htdocs\yii\framework\web\CBaseController.php(180): CBaseController->createWidget('zii.widgets.CLi...', Array)
#11 C:\xampp\htdocs\testyii\protected\views\member\index.php(20): CBaseController->widget('zii.widgets.CLi...', Array)
#12 C:\xampp\htdocs\yii\framework\web\CBaseController.php(126): require('C:\xampp\htdocs...')
#13 C:\xampp\htdocs\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#14 C:\xampp\htdocs\yii\framework\web\CController.php(872): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#15 C:\xampp\htdocs\yii\framework\web\CController.php(785): CController->renderPartial('index', Array, true)
#16 C:\xampp\htdocs\testyii\protected\controllers\MemberController.php(128): CController->render('index', Array)
#17 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): MemberController->actionIndex()
#18 C:\xampp\htdocs\yii\framework\web\CController.php(311): CInlineAction->runWithParams(Array)
#19 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#20 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#21 C:\xampp\htdocs\yii\framework\web\CController.php(1148): CFilter->filter(Object(CFilterChain))
#22 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#23 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#24 C:\xampp\htdocs\yii\framework\web\CController.php(294): CFilterChain->run()
#25 C:\xampp\htdocs\yii\framework\web\CController.php(268): CController->runActionWithFilters(Object(CInlineAction), Array)
#26 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('')
#27 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('member')
#28 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#29 C:\xampp\htdocs\testyii\index.php(13): CApplication->run()
#30 {main}
REQUEST_URI=/testyii/index.php/member
HTTP_REFERER=http://localhost/testyii/index.php/site/index
---
2016/09/13 21:39:45 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'sql6135708.Member' doesn't exist. The SQL statement executed was: SHOW FULL COLUMNS FROM `Member`.
in C:\xampp\htdocs\testyii\protected\views\member\index.php (20)
in C:\xampp\htdocs\testyii\protected\controllers\MemberController.php (128)
in C:\xampp\htdocs\testyii\index.php (13)
2016/09/13 21:39:45 [error] [exception.CDbException] exception 'CDbException' with message 'The table "Member" for active record class "Member" cannot be found in the database.' in C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php:2387
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Member))
#1 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(661): CActiveRecord->getMetaData()
#2 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(1606): CActiveRecord->getTableSchema()
#3 C:\xampp\htdocs\yii\framework\web\CActiveDataProvider.php(228): CActiveRecord->count(Object(CDbCriteria))
#4 C:\xampp\htdocs\yii\framework\web\CDataProvider.php(224): CActiveDataProvider->calculateTotalItemCount()
#5 C:\xampp\htdocs\yii\framework\web\CActiveDataProvider.php(178): CDataProvider->getTotalItemCount()
#6 C:\xampp\htdocs\yii\framework\web\CDataProvider.php(168): CActiveDataProvider->fetchData()
#7 C:\xampp\htdocs\yii\framework\zii\widgets\CBaseListView.php(125): CDataProvider->getData()
#8 C:\xampp\htdocs\yii\framework\zii\widgets\CListView.php(211): CBaseListView->init()
#9 C:\xampp\htdocs\yii\framework\web\CBaseController.php(147): CListView->init()
#10 C:\xampp\htdocs\yii\framework\web\CBaseController.php(180): CBaseController->createWidget('zii.widgets.CLi...', Array)
#11 C:\xampp\htdocs\testyii\protected\views\member\index.php(20): CBaseController->widget('zii.widgets.CLi...', Array)
#12 C:\xampp\htdocs\yii\framework\web\CBaseController.php(126): require('C:\xampp\htdocs...')
#13 C:\xampp\htdocs\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#14 C:\xampp\htdocs\yii\framework\web\CController.php(872): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#15 C:\xampp\htdocs\yii\framework\web\CController.php(785): CController->renderPartial('index', Array, true)
#16 C:\xampp\htdocs\testyii\protected\controllers\MemberController.php(128): CController->render('index', Array)
#17 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): MemberController->actionIndex()
#18 C:\xampp\htdocs\yii\framework\web\CController.php(311): CInlineAction->runWithParams(Array)
#19 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#20 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#21 C:\xampp\htdocs\yii\framework\web\CController.php(1148): CFilter->filter(Object(CFilterChain))
#22 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#23 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#24 C:\xampp\htdocs\yii\framework\web\CController.php(294): CFilterChain->run()
#25 C:\xampp\htdocs\yii\framework\web\CController.php(268): CController->runActionWithFilters(Object(CInlineAction), Array)
#26 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('')
#27 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('member')
#28 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#29 C:\xampp\htdocs\testyii\index.php(13): CApplication->run()
#30 {main}
REQUEST_URI=/testyii/index.php/member
HTTP_REFERER=http://localhost/testyii/index.php/
---
2016/09/13 21:42:27 [error] [exception.CException] exception 'CException' with message 'Property "CWebUser.homeUrl" is not defined.' in C:\xampp\htdocs\yii\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\auth\CWebUser.php(146): CComponent->__get('homeUrl')
#1 C:\xampp\htdocs\testyii\protected\controllers\SiteController.php(95): CWebUser->__get('homeUrl')
#2 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#3 C:\xampp\htdocs\yii\framework\web\CController.php(311): CInlineAction->runWithParams(Array)
#4 C:\xampp\htdocs\yii\framework\web\CController.php(289): CController->runAction(Object(CInlineAction))
#5 C:\xampp\htdocs\yii\framework\web\CController.php(268): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('login')
#7 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#8 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#9 C:\xampp\htdocs\testyii\index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/testyii/index.php/site/login
HTTP_REFERER=http://localhost/testyii/index.php/site/login
---
